### ISSUE TITLE
How to add validation on model properties?

### ISSUE THREAD

**Issue by blazkovicz** [mariusGundersen/knockout-es6#4]
Hello, I'm amazed by this project's idea and such wonderfull realization!
I'm really looking forward to using it, but I do not know how to bind knockout-validation to ViewModel fields as they are not functions now. 
Would you mind adding some examples for validation?

**Comment by mariusGundersen** [comment]
Good question! This is all mostly based on the [Knockout ES5](http://blog.stevensanderson.com/2013/05/20/knockout-es5-a-plugin-to-simplify-your-syntax/) project, and the way this is solved there (getting access to the observable that is) is to have a method that you need to call with a string. The same could be done here, for example:

``` js
class ViewModel extends ko.ViewModel{
  constructor(){
    this.a = 5;
    this.with("a").extend({required:true});
  }
  get isValid(){
    return this.with("a").isValid();
  }
}
```

I don't like having string lookups, as it makes refactoring more difficult, but I don't see any other way to do this.

**Comment by blazkovicz** [comment]
How about using arrows and storing created computeds with internal unique keys built from stringified arrow contents?

``` javascript
    class ViewModel {
      constructor() {
        //...
        this._computeds = {};
      }
      with(propertyAccessor) {
        const key = propertyAccessor.toString();
        let computed = this._computeds[key];
        if(!computed) {
          computed = ko.pureComputed(() => propertyAccessor());
          this._computeds[key] = computed;
        }
        return computed;
      }
    }
```

Main Idea is acceptable, I'll try to implement it, thanks!

**Comment by mariusGundersen** [comment]
Hmm, clever. I think both overloads of `with` can be implemented, one that takes a string and one that `toString`s an accessor as you proposed
